swagger: "2.0"
info:
  description: "API de Consulta de Usuários para POC com Keycloak federado"
  version: "1.0.0"
  title: "gov.br"
  termsOfService: "http://brasil.gov.br"
  contact:
    email: "contato@brasil.gov.br"
host: "localhost:3000"
basePath: "/v1"
schemes:
- "http"
paths:
  /usuario/{cpf}:
    get:
      tags:
      - "usuario"
      summary: "Consulta usuário por CPF"
      description: ""
      operationId: "findUsuarioPorCPF"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "cpf"
        in: "path"
        description: "O CPF do usuário a ser buscado. "
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Usuario"
        400:
          description: "Invalid username supplied"
        404:
          description: "User not found"
definitions:
  Usuario:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        example: 64019934304
      username:
        type: "string"
        example: "robson.agomes"
      firstName:
        type: "string"
        example: "Robson"
      lastName:
        type: "string"
        example: "Gomes"
    xml:
      name: "User"
